export const RESTAURANT_NAMES = [
   "Bleisure Chinese & Nigerian Cuisine",
   "Cold Stone Creamery",
   "Southern Fried Chicken",
   "Mainland Restaurant",
   "Chicken Republic",
   "Akam Chops",
   "Shawarma and Grill Station",
   "Sweet Pot Restaurant",
   "The Embarkment 24",
   "KFC",
   "Yummy Tummy",
   "Frutyz 'N' More",
   "The Edge Bistro",
   "Genesis Restaurant",
   "Rayo'lah Smoothies and Pepper Soup",
   "Movenpick Ice-cream",
   "FRIZZLERS CAFE & GRILL",
   "Nkoyo (Argungu)",
   "November Cubes",
   "Talis Fresh & Healthy Eats",
   "MMA Restaurant",
   "Downtown Takeaway",
   "Nuts & Shews",
   "Alpha Restaurant",
   "Black Olive Bistro",
   "ChopsandGrills",
   "Royal Pandoral Eatry",
   "Hoolio Food",
   "Shawarma Depot",
   "Pinkberry",
   "Native Spice Buka",
   "Red Chillies Restaurant",
   "Lomotea",
   "360Degrees",
   "IRIE",
   "Cilantro",
   "Kuk's Delight",
   "Toscakes 'N' Chops Services",
   "Juice18 Ville",
   "Zeus Kitchen and Bakery",
   "Uncle T's",
];

// List of categories

export const RESTAURANT_CATEGORIES = [
   "Alcohol",
   "Bakery and Pastry",
   "Beer",
   "Breakfast",
   "Burgers",
   "Chinese",
   "Desserts",
   "Fried Rice",
   "Grill",
   "Indian",
   "International",
   "Italian",
   "Jollof",
   "Juices",
   "Local food",
   "Nigerian",
   "Pasta",
   "Shawarma",
   "Snacks",
   "Traditional",
   "Vegetarian",
   "Chicken",
] as const;

export const MENU_CATEGORIES = [
   "Black Friday Deals",
   "MainMeal",
   "Combos",
   "Soups",
   "Protein",
   "Swallow",
   "Pastry",
   "Breakfast",
   "Burgers",
   "Chinese",
   "Desserts",
   "Rice",
   "Grill",
   "Healthy",
   "International",
   "Juices",
   "Nigerian",
   "Pizza",
   "Seafood",
   "Shawarma",
   "Snacks",
   "Proteins",
   "Drinks",
] as const;

export const menuItemsByCategory = {
   MainMeal: [
      { name: "Jollof Rice", description: "3 spoons of Long grain rice stewed with seasoned tomato sauce", price: 1700 },
      { name: "Fried Rice with Chicken", description: "Long grain rice fried with vegetables and served with chicken", price: 2000 },
      { name: "Spaghetti", description: "Very spicy hot pasta", price: 1500 },
   ],
   Combos: [
      { name: "Jollof rice with Kpanla Fish", description: "1 and 1/2 portion of Well cooked party jollof rice with peppered kpanla fish.", price: 2500 },
      { name: "Spaghetti with Boiled Egg", description: "1 and 1/2 portion Jollof spaghetti cooked and served with boiled egg", price: 1400 },
      { name: "Pizza and Drink Combo", description: "Delicious pizza served with a cold drink", price: 3000 },
   ],
   Soups: [
      { name: "Ogbono", description: "Draw soup made from dry grounded ogbono seeds", price: 1800 },
      { name: "Egusi", description: "One of Africa's number one soup made from dry melon seeds with vegetables", price: 1500 },
      { name: "Vegetable", description: "Water leaf, ugu leaf, dry fish, kpomo, and crayfish", price: 1500 },
      { name: "Efo Riro", description: "Delicious soup made with spinach, dried fish, and cow hide", price: 1500 },

      { name: "Chicken Soup", description: "Rich chicken soup with flavorful herbs and spices", price: 1000 },
      { name: "Ogbono Soup", description: "Delicious and hearty Nigerian ogbono soup", price: 1200 },
      { name: "Efo Riro", description: "Traditional Nigerian vegetable soup", price: 1400 },
   ],
   Protein: [
      { name: "Turkey", description: "Well spiced turkey", price: 4600 },
      { name: "Beef Steak", description: "Juicy and tender beef steak", price: 3000 },
      { name: "Fried Fish", description: "Succulent fried fish", price: 1500 },
      { name: "Grilled Fish", description: "Whole fish marinated and grilled", price: 12000 },
      { name: "Grilled Turkey", description: "Spicy turkey marinated in spices and grilled", price: 6000 },
      { name: "Chicken", description: "Grilled or fried chicken pieces", price: 2500 },
      { name: "Titus Fish", description: "Deep fried titus fish", price: 2000 },
      { name: "Goat Meat", description: "Goat meat in a vegetable curry sauce", price: 1500 },
      { name: "Beef", description: "Grilled or fried spicy beef", price: 1000 },

   ],
   Swallow: [
      { name: "Amala", description: "Fluffy Nigerian swallow meal made of yam flour", price: 600 },
      { name: "Semo", description: "Dough made from processed cassava, corn or wheat", price: 400 },
      { name: "Semo (each wrap)", description: "Well cooked semovita flour", price: 800 },
      { name: "Pounded Yam (each wrap)", description: "Hot boiled yam pounded in a mortar", price: 800 },
      { name: "Eba (each wrap)", description: "Fried cassava grounded into flour and combined with hot water to make a swallow", price: 700 },
      { name: "Fufu (each wrap)", description: "Soft dough made from fermented cassava", price: 700 },

   ],
   Drinks: [
      { name: "Coca-Cola 35cl Pet", description: "Fresh carbonated drink", price: 400 },
      { name: "Pepsi", description: "Fresh and fizzy cola drink", price: 400 },
      { name: "Orange Juice", description: "Freshly squeezed orange juice", price: 500 },
      { name: "Fresh Juice", description: "Fresh orange, mango, or pineapple juice", price: 2000 },
      { name: "Malt", description: "A can or bottle of malt", price: 1000 },
      { name: "Coca-Cola Original 50 CL PET", description: "Classic Coca-Cola in PET bottle", price: 750 },
      { name: "Fanta Orange 50 CL PET", description: "Fresh carbonated orange drink", price: 750 },
      { name: "Sprite 50 CL PET", description: "Fresh carbonated lemon-lime drink", price: 750 },
      { name: "Schweppes", description: "Classic Schweppes drink", price: 750 },
      { name: "Water", description: "50cl bottle of spring water", price: 400 },

   ],

   Pastry: [
      { name: "Croissant", description: "Flaky and buttery pastry", price: 500 },
      { name: "Danish", description: "Sweet pastry filled with fruit or cream", price: 600 },
   ],
   Breakfast: [
      { name: "Pancakes", description: "Fluffy and soft pancakes served with syrup", price: 1000 },
      { name: "Omelette", description: "Egg omelette with vegetables and spices", price: 800 },
   ],
   Snacks: [
      { name: "Chips", description: "Crispy potato chips", price: 300 },
      { name: "Popcorn", description: "Freshly popped popcorn", price: 200 },
   ],
   BlackFridayDeals: [
      { name: "Jollof rice + Chicken + Plantain + Free drink", description: "Jollof rice, 1 chicken, 2 plantain and take away pack and a Free drink", price: 4300 },
      { name: "Fried rice + Chicken + Plantain + Free drink", description: "Fried rice, 1 chicken, 2 plantain and take away pack with a free drink", price: 4300 },
   ],

   RiceDishes: [
      { name: "Prawn fried rice", description: "Prawn fried rice", price: 6500 },
      { name: "Shrimp fried rice", description: "Shrimp fried rice", price: 6000 },
      { name: "Special fried rice", description: "Special fried rice", price: 6000 },
      { name: "Beef fried rice", description: "Beef fried rice", price: 5700 },
      { name: "Vegetable fried rice", description: "Vegetable fried rice", price: 5000 },
      { name: "Egg fried rice", description: "Egg fried rice", price: 5000 },
      { name: "Steamed rice", description: "Steamed rice", price: 3500 },
   ],
   AfricanCuisine: [
      { name: "Jollof rice and spicy chicken", description: "Jollof rice served with spicy chicken", price: 6500 },
      { name: "Singapore fried rice", description: "Rice fried with ginger, garlic, spicy roasted red chilli paste, and a tinge of Russian sauce", price: 6000 },
      { name: "Sweet and sour chicken", description: "Bite-sized chicken coated with sweet and sour sauce", price: 6000 },
      { name: "Asun", description: "Chunks of spicy goat meat in pepper sauce", price: 5500 },
      { name: "Ofada rice and sauce", description: "Premium and authentic ofada rice with sauce", price: 5000 },
      { name: "Shrimp spring rolls", description: "2pcs of thinly sliced vegetables, shrimp, and fresh herbs in rice paper", price: 3800 },
   ],
   SoupDishes: [
      { name: "Seafood soup", description: "Rich seafood soup", price: 5500 },
      { name: "Peking soup", description: "Traditional Peking-style soup", price: 4500 },
      { name: "Corn soup", description: "Sweet corn soup", price: 3500 },
   ],
   Starters: [
      { name: "Prawn in batter", description: "Prawn in batter", price: 8000 },
      { name: "Butterfly prawn", description: "Butterfly prawn", price: 8000 },
      { name: "Crispy garlic, salt and pepper wings", description: "Chicken wings marinated in garlic and pepper sauce", price: 5500 },
      { name: "Peri peri chicken wings", description: "Fried chicken wings in Peri Peri sauce", price: 5500 },
      { name: "Deep fried chicken wings", description: "Golden deep-fried chicken wings", price: 5000 },
      { name: "BBQ chicken wings", description: "Chicken wings with BBQ sauce", price: 5000 },
      { name: "Hot and spicy chicken wings", description: "Spicy chicken wings", price: 5000 },
      { name: "Beef samosa (2pcs)", description: "Samosa stuffed with spiced beef", price: 2500 },
      { name: "Lightly salted chips", description: "Crispy potato chips lightly salted", price: 2500 },
      { name: "Vegetable spring rolls (2pcs)", description: "Spring rolls stuffed with vegetables", price: 2200 },
   ],
   NoodleDishes: [
      { name: "Chicken chow mein noodles", description: "Chow mein noodles with sliced chicken and vegetables", price: 6500 },
      { name: "Vegetable stir fry noodles", description: "Stir-fried noodles with fresh vegetables", price: 6000 },
      { name: "Chinese noodles with chicken, beef, shrimp", description: "Chinese noodles with chicken, beef, and shrimp", price: 6000 },
      { name: "Singapore noodles", description: "Singapore-style stir-fried noodles", price: 6000 },
      { name: "Chicken stir fry noodles", description: "Stir-fried noodles with chicken", price: 6000 },
   ],
   SeafoodDishes: [
      { name: "Chinese style grilled fish", description: "Grilled fish in Chinese style", price: 12000 },
      { name: "Prawn in sweet and sour sauce", description: "Prawn in tangy sweet and sour sauce", price: 8000 },
      { name: "Prawn in hot chilli sauce", description: "Prawn in hot chilli sauce", price: 8000 },
      { name: "Prawn in curry sauce", description: "Prawn cooked in curry sauce", price: 8000 },
      { name: "Fish in hot garlic sauce", description: "Fish cooked in spicy garlic sauce", price: 6500 },
      { name: "Fish in oyster sauce", description: "Fish cooked in oyster sauce", price: 6500 },
   ],
   ChickenDishes: [
      { name: "Garlic and chilli chicken", description: "Chicken cooked with garlic and chilli", price: 6000 },
      { name: "Chicken in oyster sauce", description: "Chicken cooked in oyster sauce", price: 6000 },
      { name: "Chicken in curry sauce", description: "Chicken cooked in curry sauce", price: 6000 },
      { name: "Shredded chicken in green pepper sauce", description: "Shredded chicken cooked with green pepper sauce", price: 6000 },
   ],
   BeefDishes: [
      { name: "Beef in mushroom sauce", description: "Beef cooked in rich mushroom sauce", price: 6500 },
      { name: "Beef in oyster sauce", description: "Beef cooked in oyster sauce", price: 6000 },
      { name: "Shredded beef in green pepper sauce", description: "Shredded beef with green pepper sauce", price: 6000 },
      { name: "Sliced beef in dry chilli and garlic", description: "Sliced beef cooked with chilli and garlic", price: 6000 },
   ],
   PastaDishes: [
      { name: "Chicken Stir Fry Pasta", description: "Delicious pasta stir fried with shredded chicken, spices, and vegetables", price: 4300 },
      { name: "Jollof Spaghetti", description: "Tasty spaghetti prepared in a spicy tomato sauce with vegetables", price: 3800 },
   ],
   Sides: [
      { name: "Cat Fish Pepper Soup", description: "Well seasoned catfish with spicy soup", price: 8500 },
      { name: "Asun", description: "Spicy chunks of peppered goat meat", price: 5000 },
      { name: "Goat Meat Pepper Soup", description: "A hearty African soup made with goat meat cutlets or chunks and pepper soup spice", price: 5000 },
      { name: "Plantain", description: "Well prepared plantain fried to perfection", price: 1000 },
   ],
} as const;




/* export const menuItemsByCategory = {

   MainMeal: ["Fried Rice with Chicken", "Jollof Rice with Fish", "Vegetarian Salad"],
   Combos: ["Burger and Fries Combo", "Pizza and Drink Combo", "Chicken Wings Combo"],
   Soups: ["Chicken Soup", "Mushroom Soup", "Tomato Soup", "Vegetable Soup"],
   Protein: ["Grilled Chicken", "Beef Steak", "Tofu", "Fried Fish"],
   Swallow: ["Amala", "Pounded Yam", "Eba", "Semo"],
   Drinks: ["Coke", "Pepsi", "Orange Juice", "Lemonade"],
   pastry: ["Croissant", "Baguette", "Danish", "Muffin", "Bagel", "Scones", "Eclair"],
   breakfast: ["Pancakes", "Omelette", "French Toast", "Eggs Benedict"],
   burgers: ["Cheeseburger", "Bacon Burger", "Veggie Burger", "Chicken Burger"],
   chinese: ["Sweet and Sour Chicken", "Kung Pao Chicken", "Spring Rolls", "Peking Duck"],
   desserts: ["Chocolate Cake", "Apple Pie", "Cheesecake", "Ice Cream"],
   rice: ["Fried Rice", "Jollof Rice", "Biryani", "Sushi Rice"],
   grill: ["Grilled Chicken", "BBQ Ribs", "Grilled Steak", "Grilled Salmon"],
   Healthy: ["Quinoa Salad", "Avocado Salad", "Green Smoothie", "Acai Bowl"],
   international: ["Tacos", "Sushi", "Pizza", "Paella", "Ramen"],
   juices: ["Orange Juice", "Apple Juice", "Carrot Juice", "Watermelon Juice"],
   nigerian: ["Moi Moi", "Fried Plantain", "Fried Yam", "Akara"],
   pizza: ["Pepperoni Pizza", "Margherita Pizza", "BBQ Chicken Pizza", "Hawaiian Pizza"],
   seafood: ["Grilled Salmon", "Shrimp Scampi", "Lobster Tail", "Fish Tacos"],
   shawarma: ["Chicken Shawarma", "Beef Shawarma", "Lamb Shawarma", "Falafel Wrap"],
   snacks: ["Chips", "Popcorn", "Nachos", "Pretzels", "Fries"],
   soup: ["Chicken Soup", "Bitterleaf Soup", "Ogbono Soup", "Efo Riro", "Banga Soup"],
   drinks: ["Coke", "Pepsi", "Lemonade", "Iced Tea", "Beer", "Wine"],
 } as any; */